RP-1: Задание 1. Реализация прогноза курса валют
kbashkatova/rateprediction pull request #1
Opened 2023-10-17 17:12 UTC by kbashkatova

2023-10-19 16:26 UTC, JiubRedeemer requested changes

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/Application.java
> +        while (true) {
Бесконечные циклы плохо - подумай над механизмом выхода из приложения

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/model/Currency.java
> +    EUR("EUR", "Евро", "/EUR.csv"),
Пути к файлам выноси в настройки. Если поменяешь путь - весь проект отвалится) (относится ко всем местам где путь строкой, не только здесь)

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/data/processor/CurrencyDataProcessor.java
> +        LinkedList<CurrencyData> currencyDataList = new LinkedList<>();
Если по логике переменную перетирать не надо - по дефолту ставь final. Иначе можешь случайно что-то перетереть и получить неожиданный результат :)

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/UserRequestForecastGenerator.java
> +    public static String generateForecast() {
Божественный метод - плохо, здесь и вычитывание из консоли, и парсинг запроса, и генерация прогноза. Декомпозируй.

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/UserRequestForecastGenerator.java
> +        while (isNull(parsedRequest)) {
Помимо проверки на null следует проверить на заполненность полей, ибо дальше ты как пример делаешь selectForecastGenerator(parsedRequest.getRateType()), если rateType = null - выкинет npe

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/algorithm/RateCalculator.java
> +                    .filter(data -> data.getDate().isBefore(currentDate))
Можно поместить в один фильтр

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/algorithm/RateCalculator.java
> +                    .limit(7)
7 - magicNumber - вынеси в константу и дай человекочитаемое название

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/algorithm/RateCalculator.java
> +            if (previousData.size() < 7) {
та же история с magicNumber

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +                double averageCurs = RateCalculator.calculateAverageRateFromLastSevenRates(currencyDataList, currentDate);
Транслит ненада, да и именовать надо единообразно, назови averageRate

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +                List<CurrencyData> newCurrencyData = fillMissingDates(currencyDataList, nextDate, targetDate);
"new" не в контексте new/current плохая практика, не понятно почему new, назови более связно с контекстом этой переменной

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/generator/WeeklyCurrencyForecastGenerator.java
> +        StringBuilder sb = new StringBuilder();
непонятный нейминг переменных, название переменной должно передавать её суть

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/utils/DateUtils.java
> +    private static final String DATE_FORMAT = "M/d/yyyy";
Лучше использовать общепринятый формат, например ISO
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/data/processor/CurrencyDataProcessor.java
> +    public CurrencyDataProcessor(String filePath, String currencyName) {
Зачем тут currencyName?

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +        if (forecastType == RateType.TOMORROW) {
Сравнения через == это сравнения по ссылке, сделать через equals

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +            throw new RuntimeException("Failed to fill missing dates", e);
Конкретизируй тип ошибки

2023-10-19 16:26 UTC, JiubRedeemer commented on src/main/java/ru/liga/rateforecaster/data/processor/CurrencyDataProcessor.java
> +            InputStreamReader reader = new InputStreamReader(Objects.requireNonNull(resourceStream));
Objects.requireNonNull - излишен, выше уже есть проверка на null и проброс исключения

2023-10-20 11:06 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/UserRequestForecastGenerator.java
> +        while (isNull(parsedRequest)) {
корректность заполнения объекта ParsedRequest выполняется в классе RequestParser перед созданием объекта

2023-10-20 11:07 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/UserRequestForecastGenerator.java
> +        while (isNull(parsedRequest)) {
Здесь проверка на null нужна для предоставления пользователю возможности повторить запрос, если введенная строка была некорректна и объект ParsedRequest не был создан.

2023-10-20 11:08 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/data/processor/CurrencyDataProcessor.java
> +    public CurrencyDataProcessor(String filePath, String currencyName) {
Предполагалась запись уже рассчитанных курсов в файл для последующего использования обновленных данных. Так как функционал не будет реализован, поле удаляю.

2023-10-20 11:34 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/Application.java
> +        while (true) {
Предусмотрен механихм завершения программы.

2023-10-20 11:34 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/model/Currency.java
> +    EUR("EUR", "Евро", "/EUR.csv"),
Пути к файлам вынесены в файл application.properties.

2023-10-20 11:35 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/data/processor/CurrencyDataProcessor.java
> +        LinkedList<CurrencyData> currencyDataList = new LinkedList<>();
Во внесенных изменениях переменные объявлены как final в нужных местах.

2023-10-20 11:35 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/UserRequestForecastGenerator.java
> +    public static String generateForecast() {
Метод поделен на более мелкие согласно логике, содержащейся в них.

2023-10-20 11:45 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/algorithm/RateCalculator.java
> +                    .filter(data -> data.getDate().isBefore(currentDate))
Перенесено в один фильтр.

2023-10-20 11:46 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/algorithm/RateCalculator.java
> +                    .limit(7)
7 вынесена в константу

2023-10-20 11:46 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/algorithm/RateCalculator.java
> +            if (previousData.size() < 7) {
вынесено в константу

2023-10-20 11:46 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +                double averageCurs = RateCalculator.calculateAverageRateFromLastSevenRates(currencyDataList, currentDate);
Скорректировано

2023-10-20 11:46 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +                List<CurrencyData> newCurrencyData = fillMissingDates(currencyDataList, nextDate, targetDate);
Скорректировано

2023-10-20 11:46 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/generator/WeeklyCurrencyForecastGenerator.java
> +        StringBuilder sb = new StringBuilder();
Скорректировано

2023-10-20 11:47 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +            throw new RuntimeException("Failed to fill missing dates", e);
Скорректировано

2023-10-20 11:47 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/forecast/generator/CurrencyForecastGenerator.java
> +        if (forecastType == RateType.TOMORROW) {
Скорректировано

2023-10-20 11:47 UTC, kbashkatova commented on src/main/java/ru/liga/rateforecaster/data/processor/CurrencyDataProcessor.java
> +            InputStreamReader reader = new InputStreamReader(Objects.requireNonNull(resourceStream));
Скорректировано

2023-10-23 12:54 UTC, IgorSeyl commented
- Почистить неиспользуемые импорты
- Хорошая практика - сообщения доставать из пропертей, в целях повторного использования. Можно создать Resource Bundle 'messages' и в ней 2 файла, с англоязычными и с русскоязычными сообщениями и выводить их каким-нибудь messageService'ом
- Енумы и модели - это не одно и тоже, стоит разбить на разные пакеты: model и enum

Опционально
- Пути к файлам обычно прописывают не прямо, если приложение может запускаться на разных операционках, например можно использовать File.separator

2023-10-27 20:25 UTC, merged

2023-11-03 12:19 UTC, boris-dev commented on src/main/java/ru/liga/rateforecaster/forecast/algorithm/RateCalculator.java
> +                    .filter(data -> data.getDate().isBefore(currentDate))
> Можно поместить в один фильтр

Вообще лучше два разных фильтра, так они считываются проще и находятся на разных строках, иначе по этой логике можно наворочить и три проверки, а они будут уже сложно восприниматься и требовать больше мозготоплива. Ну и если вдруг упадёт то будет понятно на какой строке. Можно в один фильтр если ты вынесешь в метод и дашь какое-нибудь хорошее название.

2023-11-03 13:14 UTC, boris-dev commented
В проекте много статики, нужно отойти от неё в сторону объектов с DI через конструкторы.